version: "3.7"
services:

  redis:
    image: redis
    command: redis-server --appendonly yes
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - "./data:/data"